##### 1. Create a numpy array starting from 2 till 50 with a stepsize of 3

In [1]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


##### 2. Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [6]:
list1 = []
list2 = []

for i in range(5):
    n = int(input())
    list1.append(n)
print("List1: ",list1)    

for y in range(5):
    n = int(input())
    list2.append(n)
print("List2: ",list2)  

array1 = np.array(list1)
array2 = np.array(list2)
list3 = np.concatenate((array1, array2))
print("Concatenated Array: ", list3)
list4 = np.sort(list3)
print("Sorted Array: ", list4)

3
6
12
2
89
List1:  [3, 6, 12, 2, 89]
56
23
1
6
3
List2:  [56, 23, 1, 6, 3]
Concatenated Array:  [ 3  6 12  2 89 56 23  1  6  3]
Sorted Array:  [ 1  2  3  3  6  6 12 23 56 89]


##### 3. Write a code snippet to find the dimensions of a ndarray and its size.

In [13]:
array1 = np.arange(5,20,2)
print("Array: ",array1)
print("Dimension: ",array1.ndim)
print("Size: ",array1.size)

Array:  [ 5  7  9 11 13 15 17 19]
Dimension:  1
Size:  8


##### 4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [19]:
array1 = ([21,54,78,0])
array2 = np.reshape(array1, (2,2))
print("2D Array: \n",array2)

2D Array: 
 [[21 54]
 [78  0]]


##### 5.Consider two square numpy arrays. Stack them vertically and horizontally.

In [23]:
array1 = np.array([[12,34],[56,76]])
array2 = np.array([[20,40],[60,80]])
vertical = np.vstack((array1,array2))
horizontal = np.hstack((array1,array2))
print("Vertical :\n",vertical)
print("\nHorizontal :\n",horizontal)

Vertical :
 [[12 34]
 [56 76]
 [20 40]
 [60 80]]

Horizontal :
 [[12 34 20 40]
 [56 76 60 80]]


##### 6. How to get unique items and counts of unique items?

In [28]:
array1 = np.array([1,2,1,3,5,3,4,1])

(unique, counts) = np.unique(array1, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 2]
 [4 1]
 [5 1]]
